packages:
  - .
  - ./sim-one-cli
allowBuilds:
  '@google/genai': true
  '@mongodb-js/zstd': true
  esbuild: true
  node-liblzma: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@google/genai'
  - '@mongodb-js/zstd'
  - esbuild
  - node-liblzma
  - onnxruntime-node
  - protobufjs
  - sharp
  - workerd
verifyDepsBeforeRun: true
