packages:
  - '.'
allowBuilds:
  '@google/genai': true
  '@mongodb-js/zstd': true
  esbuild: true
  node-liblzma: true
  onnxruntime-node: false
  protobufjs: true
  sharp: true
  wasm-pack: false
  workerd: true
verifyDepsBeforeRun: true
